### ISSUE TITLE
[Feature request]: Replace `nOperatingMode` of `MceManualMotionIO` by a boolean

### ISSUE THREAD

**Issue by yeu-rioual** [YaskawaEurope/mlx-examples#43]
`nOperatingMode` input expects a machine operating mode input that was specific for a certain application.

We should make it a boolean and rename it like `bJogMode` or `bManualMode`.

**Comment by yeu-degroot** [comment]
It would not be just one bit. With operating mode, we wanted to cover also `semi-auto`.
So if you want to create bits, it would need at least three:

```yaml
  nOperatingMode:
    description: |
      Machine operating mode.
      This signal is produced by [`MceOperatingMode`](../../functions/mceoperatingmode).
    type: USINT
    default_value: "0"
    comment: "input: machine operating mode [0=none, 1=manual, 2=semi-auto, 3=auto]"
    legend:
      "0": none
      "1": manual mode
      "2": semi-automatic mode (step by step)
      "3": automatic mode
```

And these mode bits would need to be passed to lower level functions.
The original idea was to use one operating mode (`usint`) and pass that, so that lower level functions have all information.
